# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Example-InstantCRUD
version:      v0.0.8
version_from: lib/Catalyst/Example/InstantCRUD.pm
installdirs:  site
requires:
    Catalyst:                      5.66
    Catalyst::Helper::Model::DBIC::Schema: 0
    Catalyst::Model::DBIC:         0
    Catalyst::Plugin::DefaultEnd:  0
    Catalyst::View::TT:            0.21
    DBIx::Class:                   0
    DBIx::Class::Loader:           0
    DBIx::Class::Schema:           0
    File::Spec:                    0
    HTML::Entities:                0
    HTML::Widget:                  0
    Template::Plugin::Class:       0
    Test::More:                    0
    URI::Escape:                   0
    version:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
