--- #YAML:1.0
name:               Catalyst-Example-InstantCRUD
version:            0.0.21
abstract:           A CRUD scaffolding for Catalyst.
author:
    - <Zbigniew Lukasiak> <<zz bb yy @ gmail.com>>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Catalyst::Devel:      1.00
    Catalyst::Helper::Model::DBIC::Schema:  0
    Catalyst::Model::DBIC::Schema:  0
    Catalyst::Plugin::ConfigLoader:  0
    Catalyst::Plugin::Session::State::Cookie:  0
    Catalyst::Plugin::Session::Store::FastMmap:  0
    Catalyst::Plugin::Static::Simple:  0
    Catalyst::Runtime:    5.7000
    Catalyst::View::TT:   0.21
    DBIx::Class:          0.08003
    DBIx::Class::ResultSet::RecursiveUpdate:  0
    DBIx::Class::Schema::Loader:  0.03
    File::Slurp:          0
    File::Spec:           0
    List::Util:           0
    Path::Class:          0
    Pod::Usage:           0
    Rose::HTMLx::Form::DBIC:  0
    Rose::HTMLx::Form::DBIC::FormGenerator:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
