--- #YAML:1.0
name:               Catalyst-Example-InstantCRUD
version:            0.035
abstract:           A CRUD scaffolding for Catalyst.
author:
    - <Zbigniew Lukasiak> <<zz bb yy @ gmail.com>>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Catalyst::Devel:      1.00
    Catalyst::Helper::Model::DBIC::Schema:  0
    Catalyst::Model::DBIC::Schema:  0.29
    Catalyst::Plugin::ConfigLoader:  0
    Catalyst::Plugin::Session::State::Cookie:  0
    Catalyst::Plugin::Session::Store::FastMmap:  0
    Catalyst::Plugin::Static::Simple:  0
    Catalyst::Plugin::Unicode:  0
    Catalyst::Runtime:    5.8000
    Catalyst::View::TT:   0.21
    DBIx::Class:          0.08003
    DBIx::Class::ResultSet::RecursiveUpdate:  0
    DBIx::Class::Schema::Loader:  0.03
    DBIx::Class::UTF8Columns:  0
    File::Slurp:          0
    HTML::FormHandler:    0.26
    HTML::FormHandler::Generator::DBIC:  0.03
    HTML::FormHandler::Model::DBIC:  0.04
    List::Util:           0
    Path::Class:          0
    Pod::Usage:           0
    String::Random:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
